# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.example_floor_clock.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'example_floor_clock', 'function_path': 'animated_java:example_floor_clock/animations/update/apply_frame'}
data remove storage aj:temp args
$execute store result storage aj:temp args.frame int 1 run scoreboard players set @s aj.update.frame $(frame)
execute at @s run function animated_java:example_floor_clock/animations/update/zzz/apply_frame with storage aj:temp args