# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.example_floor_clock.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'example_floor_clock', 'function_path': 'animated_java:example_floor_clock/animations/update/next_frame'}
execute if score @s aj.update.frame matches 20.. run scoreboard players set @s aj.update.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.update.frame
execute at @s run function animated_java:example_floor_clock/animations/update/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.update.frame 1