# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.example_floor_clock.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'example_floor_clock', 'function_path': 'animated_java:example_floor_clock/animations/update/stop'}
tag @s remove aj.example_floor_clock.animation.update.playing
scoreboard players set @s aj.update.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:example_floor_clock/animations/update/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only