# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.example_floor_clock.root] run return 0
execute on passengers if entity @s[tag=aj.example_floor_clock.data] unless data entity @s {data:{rigHash: 'bfb16df248f322ff539b8b434b503616caed616d07930d42026fb9897798c4fa'}} on vehicle run function animated_java:example_floor_clock/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1