# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:example_floor_clock/animations/update/zzz/apply_frame {frame: 19}
scoreboard players add @s aj.update.frame 1