# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_bone) {transformation: [-1f,0f,0f,0f,0f,1f,0f,2.0313f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone1) {transformation: [-1.75f,0f,0f,0.375f,0f,1.75f,0f,0f,0f,0f,-1.75f,0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bone2) {transformation: [-1f,0f,0f,0f,0f,1f,0f,2.25f,0f,0f,-1f,0.4531f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}