from typing import List
import os
import json
import shutil

# from gamepack.mcfunction import *
# from gamepack.advancement import *

def dict_to_directories(data: dict, parent_path=""):
    """
    递归将字典结构转换为文件系统目录和文件
    :param data: 字典结构，键为目录/文件名，值为子字典（目录）或字符串（文件内容）
    :param parent_path: 父目录路径，默认为当前目录
    """
    for name, content in data.items():
        current_path = os.path.join(parent_path, name)
        
        if isinstance(content, dict):
            # 创建目录并递归处理子字典
            os.makedirs(current_path, exist_ok=True)
            dict_to_directories(content, current_path)
        elif isinstance(content, str):
          # 创建文件并写入内容（自动添加换行符）
          try:
              with open(current_path, 'w', encoding='utf-8') as f:
                  f.write(content + '\n')  # 确保内容以换行符结尾
          except (IOError, PermissionError) as e:
              print(f"文件创建失败: {current_path}, 错误: {e}")
        elif content != None and isinstance(content, object):
          try:
              content.gen(current_path)
          except (IOError, PermissionError) as e:
              print(f"文件创建失败: {current_path}, 错误: {e}")
        else:
          if content == None:
            return
          else:
            print(f"警告: 忽略不支持的类型 {type(content)} (路径: {current_path})")

class Pack:
  def __init__(self, pack_name: str):
    self.pack_name = pack_name
    
    self.data = {}
    self.pack_mcmeta = {
      "pack": {
        "pack_format": 0,
        "description": "pack generated by cubi"
      }
    }
    
  def add_functions(self):
    pass
    return {}

  def add_advancements(self):
    pass
    return {}

  def gen(self, out_path: str, namespace: str):
    if not os.path.exists(out_path):
      raise FileExistsError(f'路径不存在：{out_path}')
    
    pack_path = os.path.join(out_path, self.pack_name) 
    if os.path.exists(pack_path):
      shutil.rmtree(pack_path)
    if not os.path.exists(pack_path):
      os.makedirs(pack_path)
      
    mcfunctions = self.add_functions()
    advancements = self.add_advancements()
    
    if mcfunctions:
      self.data[namespace]['function'] = mcfunctions
    if advancements:
      self.data[namespace]['advancement'] = advancements

    pack_structure = {
      "data": self.data,
      "pack.mcmeta": json.dumps(self.pack_mcmeta, indent=2)
    }
    
    dict_to_directories(pack_structure, pack_path)  
  
