# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers run function animated_java:example_floor_clock/remove/zzz/this/recursively_kill_passengers
kill @s