# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.cubi.root] run return 0
execute on passengers if entity @s[tag=aj.cubi.data] unless data entity @s {data:{rigHash: '2c4a36bfaf15d92915bdb29761dc7efa5f01a75f147f2d2bf780b2b5d36041b2'}} on vehicle run function animated_java:cubi/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1